baseURL = 'https://sjs851009.github.io/'
languageCode = 'en-us'
title = "Junseok's Website"
theme = ["my-theme"]
publishDir = "docs"

[menu]
  [[menu.menu]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 4
